# Generated by Django 5.2.4 on 2025-08-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auther', '0002_ngo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
