# Generated by Django 5.2.4 on 2025-08-06 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auther', '0003_ngo_address'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
