# Generated by Django 5.2.4 on 2025-08-05 18:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auther', '0002_ngo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('Home Essentials', 'Home Essentials'), ('Furniture', 'Furniture'), ('Clothing & Footwear', 'Clothing & Footwear'), ('Hygiene Essentials', 'Hygiene Essentials'), ('Education Supplies', 'Education Supplies'), ('Childcare and Toys', 'Childcare and Toys'), ('Medical Supplies', 'Medical Supplies'), ('Bedding & Shelter', 'Bedding & Shelter')], default='Home Essentials')),
                ('title', models.CharField(blank=True, default='Null', max_length=50)),
                ('image', models.ImageField(blank=True, default='fallback.png', upload_to='')),
                ('quantity', models.IntegerField(default=1)),
                ('verified', models.BooleanField(default=False)),
                ('donated', models.BooleanField(default=False)),
                ('recieved', models.BooleanField(default=False)),
                ('submittedon', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(blank=True, null=True)),
                ('donationdate', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('ngo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auther.ngo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
