# Generated by Django 5.2.4 on 2025-08-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfuncs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='verified',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending'),
        ),
    ]
