# Generated by Django 5.2.4 on 2025-08-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfuncs', '0002_alter_donation_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='rejectionReason',
            field=models.CharField(blank=True, null=True),
        ),
    ]
