# Generated by Django 5.2.4 on 2025-08-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfuncs', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, default='New Notification', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('rejected', 'rejected'), ('accepted', 'accepted'), ('info', 'info')], default='info'),
        ),
    ]
