# Generated by Django 5.2.4 on 2025-08-06 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auther', '0003_ngo_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ngorequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('Home Essentials', 'Home Essentials'), ('Furniture', 'Furniture'), ('Clothing & Footwear', 'Clothing & Footwear'), ('Hygiene Essentials', 'Hygiene Essentials'), ('Education Supplies', 'Education Supplies'), ('Childcare and Toys', 'Childcare and Toys'), ('Medical Supplies', 'Medical Supplies'), ('Bedding & Shelter', 'Bedding & Shelter')], default='Home Essentials', max_length=100)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auther.ngo')),
                ('usersissuing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
