# Generated by Django 5.2.4 on 2025-08-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngofunc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngorequests',
            name='address',
        ),
    ]
